DinnersReady/Models/Ingredients/Ingredient.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DinnersReadyCore.Models.FoodCategories;


namespace DinnersReadyCore.Models.Ingredients
{
    public class Ingredient
    {
        [Key]
        public int IngredientId { get; set; }


        //Ingredient Name in the Singular form
        [Required]
        [StringLength(50)]
        public string NameSingular { get; set; }


        //Ingredient Name in the Plural form
        [Required]
        [StringLength(50)]
        public string NamePlural { get; set; }


        //Food Category: Beef, Pork, Nuts, Breads, Cereals...
        //so users can search and find this ingredient
        //when the Recipe Ingredients display they will be ordered ny Food Category then Name
        [Required]
        public int FoodCategoryId { get; set; }
        [ForeignKey("FoodCategoryId")]
        public virtual FoodCategory FoodCategorys { get; set; }


        //This holds the Type of the Unit Of Measure, namely:
        //    Dry or Liquid or Size or Temp
        // Dry Measure (g, kg, oz, lb, tsp(5g approx), tbsp(15g approx)), 
        // Liquid Measure (L, ml, fl oz, pints, tsp(5ml), tbsp(15ml)),
        // Size Measure (cm, inch),
        // Temperature Measure (C, F, Gas mark)
        //It tells us which range of potential measure may need to be supplied for 
        //the ingredient when it's being viewed
        [Required]
        [StringLength(15)]
        public string TypeOfMeasureName { get; set; }


        //Future Use: When an Ingredient is manually enetered it will be flagged for Admin review
        //ReviewedStatus is false before review and true afterwards
        //a null value implies the Ingredient was hard-coded at setup
        public bool? ReviewedStatus { get; set; }


        //Conversion rate Gram / Millilitre to Teaspoon (UK) for this Ingredient
        public double OneGramToTeaspoonUK { get; set; }


        //Conversion rate Teaspoon (UK) to Gram / Millilitre for this Ingredient
        public double OneTeaspoonUKToGram { get; set; }


    }
}

DinnersReady/Models/Ingredients/IngredientSmall.cs
namespace DinnersReadyCore.Models.Ingredients
{
    public class IngredientSmall
    { 

        public int IngredientId { get; set; }


        //Ingredient Name in the Singular form   
        public string NameSingular { get; set; }

    }
}

DinnersReady/ViewModels/AddRecipe/AddVM.cs
using System.Collections.Generic;


namespace DinnersReadyCore.ViewModels.AddRecipe
{
    public class AddVM
    {

        public string Name { get; set; }

        public bool RecipeAddedSuccess { get; set; }

        public List<string> MainFoodCategories { get; set; }

        public List<string> IngredientsLike { get; set; }

        public List<string> UnitsOfMeasureSymbols { get; set; }

    }
}

DinnersReady/ViewModels/EditRecipe/EditVM.cs
using System.Collections.Generic;
using DinnersReadyCore.Models.Recipes;


namespace DinnersReadyCore.ViewModels.EditRecipe
{
    public class EditVM
    {
        public RecipeWithDetails localRecipe { get; set; }

        public List<string> MainFoodCategories { get; set; }

        public List<string> IngredientsLike { get; set; }

        public List<string> UnitsOfMeasureSymbols { get; set; }

    }
}

DinnersReady/ViewModels/ViewRecipe/ViewVM.cs
using System.Collections.Generic;
using DinnersReadyCore.Models.Recipes;


namespace DinnersReadyCore.ViewModels.ViewRecipe
{
    public class ViewVM
    {
        public RecipeWithDetails localRecipe { get; set; }

        public List<string> MainFoodCategories { get; set; }

        public List<string> IngredientsLike { get; set; }

        public List<string> UnitsOfMeasureSymbols { get; set; }

    }
}

DinnersReady/Controllers/AddController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using DinnersReadyCore.Models;
using DinnersReadyCore.Models.Recipes;
using DinnersReadyCore.Models.Ingredients;
using DinnersReadyCore.ViewModels.AddRecipe;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.AspNetCore.Builder;
using System.Reflection.Metadata.Ecma335;



namespace DinnersReadyCore.Controllers.Add
{
    public class AddController : Controller
    {

        private readonly bool recipeAdded = false;
        private readonly IRecipeRepository _recipeRepository;


        public AddController(IRecipeRepository recipeRepository)
        {
            _recipeRepository = recipeRepository;
        }
        

        [HttpGet]
        public ActionResult Recipe()
        {
            AddVM addViewModel = new AddVM { };
  
            addViewModel.RecipeAddedSuccess = recipeAdded;
            addViewModel.MainFoodCategories = _recipeRepository.GetMainFoodCategories();

            return PartialView("_AddRecipe", addViewModel);
        }


        [HttpPost]
        public JsonResult ProcessNewRecipe(string recipeName, string description,
            string course, string cookingMethod, string servings, string cookingTime,
            List<string>  ingredientsName, List<string> amountsName, List<string> uomName,
            List<string> commentsName, List<string> instructionsName, List<string> instructionTempName,
            List<string> originalTemperatureUoMName,
            string additionalNotes, string goesWithNotes, string season, string cuisine,
            string anevent, string dietaryRequirement, bool freezable, string mainFoodCategory,
            string recipeIdt)
        {
           
            return Json(_recipeRepository.ProcessRecipe(recipeName, description,
                course, cookingMethod, servings, cookingTime, additionalNotes,
                goesWithNotes, season, cuisine, anevent, dietaryRequirement,
                freezable, mainFoodCategory, ingredientsName, amountsName, uomName, commentsName,
                instructionsName, instructionTempName, originalTemperatureUoMName, recipeIdt));     
        }


        [HttpPost] 
        public string ProcessNewImage(IFormFile file)
        {
            string recipeIdent = _recipeRepository.ProcessImage(file);
            return recipeIdent;
        }

   
        public bool CheckRequiredFields(List<string> requiredFields)
        {
            bool fieldsCompleted = true;
            foreach(string temp in requiredFields)
            {
                if (String.IsNullOrEmpty(temp))
                {
                    fieldsCompleted = false;
                }
            }
            return fieldsCompleted;
        }


        [HttpGet]
        public JsonResult GetIngredients(string ingredient)
        {
            string localIngredient = ingredient;
            var numberOfIngredients = 20;
            List<string> ingredientsLikeList = _recipeRepository.GetIngredientsLike(localIngredient, numberOfIngredients);

            return Json(ingredientsLikeList.ToList());
        }


        [HttpGet]
        public JsonResult GetUnitsOfMeasureAdd(string ingredient)
        {
            string localIngredient = ingredient;
            List<string> unitsOfMeasureList = _recipeRepository.GetUnitsOfMeasureSymbolsForIngredientType(localIngredient);

            return Json(unitsOfMeasureList.ToList());
        }


        [HttpGet]
        public JsonResult GetTemperatureUnitsOfMeasure()
        {
            return Json(_recipeRepository.GetTemperatureUnitsOfMeasures().ToList());
        }


        [HttpGet]
        public JsonResult GetFoodCategories()
        {
            List<string> foodCategoryNames = _recipeRepository.GetFoodCategories().ToList();
            return Json(foodCategoryNames);
        }


        [HttpGet]
        public JsonResult ProcessNewIngredient(string ingredientNameSingular, string ingredientNamePlural,
            string ingredientFoodCategory, string ingredientDryOrWetMeasure)
        {
            return Json(_recipeRepository.CheckNewIngredient(ingredientNameSingular, ingredientNamePlural,
                ingredientFoodCategory, ingredientDryOrWetMeasure));
        }


        [HttpGet]
        public PartialViewResult GetNewIngredientView()
        {

            return PartialView("_Ingredient");
        }


        [HttpPost]
        public Boolean AddIngredient(string newIngredientSingularName, string newIngredientPluralName,
            string newIngredientFoodCategoryName, string dryOrWetMeasureName)
        {
            Boolean IngredientAdded = _recipeRepository.AddNewIngredient(newIngredientSingularName,
                newIngredientPluralName, newIngredientFoodCategoryName, dryOrWetMeasureName);

            return IngredientAdded;
        }


        [HttpGet]
        public void DeleteImageOrphans()
        {
            _recipeRepository.DeleteRecipeImageOrphans();
        }


    } // close class
}  // close namespace

DinnersReady/Controllers/ListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using DinnersReadyCore.Models.Recipes;



namespace DinnersReadyCore.Controllers.List
{
    public class ListController : Controller
    {

        // private readonly bool recipeAdded = false;
        private readonly IRecipeRepository _recipeRepository;


        public ListController(IRecipeRepository recipeRepository)
        {
            _recipeRepository = recipeRepository;
        }


        // GET: List
        public ActionResult _AllRecipes()
        {
            return PartialView();
        }


        [HttpPost]
        public JsonResult GetAllRecipes()
        {
            return Json(_recipeRepository.GetAllTheRecipes());
        }

    }
}

DinnersReady/Views/Shared/_AllRecipes.cshtml
<link href="~/css/site.css" rel="stylesheet" />

<div id="preloader"></div>

<h1 class="backgroundTitleProps1">Welcome to Dinner's Ready!</h1>
<h2 class="backgroundTitleProps2">Here are our dishes:</h2>

<br />
<hr class="recipesBreak" />

<link href="~/css/jquery.dataTables.min.css" rel="stylesheet" />

<div id="recipesLoading"></div>

<container id="recipesContainer" class="d-flex flex-row align-content-stretch backgroundTableProps">
</container>

<div class="callout">
    <div class="callout-header">Important</div>
    <span id="webDevCalloutBtn" class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
    <div class="callout-container">
        <p>
            This is not a real recipe website! <br>
            It is a Web Development project undertaken for educational purposes.
        </p>
    </div>
</div>

</div>

<script>
    var url1 = "/js/jquery.dataTables.min.js";
    $.getScript(url1);
</script>

<script>
    var url2 = "/js/allRecipes.js";
    $.getScript(url2);
</script>

DinnersReady/Views/Shared/_Ingredient.cshtml
<div id="formDiv" class="showHide">
    <form id="addIngredientFormId"  asp-controller="Add" asp-action="AddIngredient" method="POST" role="form" onsubmit="processNewIngredient()">
        <div class="form-group">

            <div id="ingredientNameFeedbackDivId" class="hide">
                <p id="ingredientNameFeedbackParaId" class="hide"></p>
            </div>

            <fieldset>
                <legend>Name Singular:</legend>
                <input type="text" id="newIngredientSingularId" name="newIngredientSingularName" required />
            </fieldset>

            <fieldset>
                <legend>Name Plural:</legend>
                <input type="text" id="newIngredientPluralId" name="newIngredientPluralName" required />
            </fieldset>

            <fieldset>
                <legend>Food Category:</legend>
                <select id="newIngredientFoodCategoryId" name="newIngredientFoodCategoryName" style="width:150px" required />
            </fieldset>

            <fieldset>
                <legend>Dry or Wet Measure?</legend>
                <select id="dryOrWetMeasureId" name="dryOrWetMeasureName" style="width:100px" required>
                    <option disabled selected placeholder="-- select --" required></option>
                    <option value="Dry">Dry</option>
                    <option value="Wet">Wet</option>
                </select>
            </fieldset>

            <br />
            <button type="button" class="btn btn-default btn-success btn-clock" style="display: inline;"
                    id="addIngredientButton" value="Submit" onclick="processIngredient()">
                <span class="glyphicon glyphicon-off">Submit</span>
            </button>
            <br />

            <br />                                               
            <button type="button" class="btn btn-default btn-danger btn-clock" style="display: inline;"
                    id="closeAddIngredientFormButton" onclick="closeAddIngredientForm()">
                <span class="glyphicon glyphicon-off">Cancel</span>
            </button>

        </div>
    </form>
    <hr />
</div>

<script>
    var url = "/js/addIngredient.js";
    $.getScript(url);
</script>

DinnersReady/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="imag/ico" href="~/images/favicon.ico">
    <title>Dinner's Ready!</title>
    <link href="~/css/reset.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-reboot.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-grid.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/alertify/alertify.min.css" />
    <link rel="stylesheet" href="~/css/alertify/themes/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Animate.css" />
    <link href="~/lib/fontawesome-free-5.15.1-web/css/all.min.css" rel="stylesheet" />
    <link href="~/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
</head>

<body data-spy="scroll" data-target="#pb-navbar" data-offset="200">

    <link href="~/lib/bootstrap/dist/css/bootstrap-grid.css" rel="stylesheet">
    <nav class="navbar h-navbar navbar-expand-md site-navbar p-0 fixed-top" role="navigation" id="pb-navbar">
        <div class="container navContainer">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsCollapse"
                aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <a asp-controller="Home" asp-action="Index" class="navbar-brand">
                <img id="logo" class="logo" src="~/images/icon.svg" alt="Dinner's Ready Logo"
                    asp-append-version="true" />
            </a>

            <div class="collapse navbar-collapse justify-content-md-center" id="navbarsCollapse"
                style="font-size: 20px">

                <ul class="nav navbar-nav ml-auto">

                    <li class="nav-link">
                        <a asp-controller="List" asp-action="_AllRecipes" class="btn btn-primary" data-ajax="true"
                            data-ajax-loading="#viewLoading" data-ajax-method="GET" data-ajax-mode="replace"
                            data-ajax-update="#viewTarget">
                            VIEW RECIPES
                        </a>
                    </li>

                    <li class="nav-link">
                        <a asp-controller="Add" asp-action="Recipe" class="btn btn-primary" data-ajax="true"
                            data-ajax-loading="#viewLoading" data-ajax-method="GET" data-ajax-mode="replace"
                            data-ajax-update="#viewTarget">
                            ADD RECIPE
                        </a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">

        @RenderBody()

        <div id="viewTarget"></div>

    </div>

    <hr class="recipesBreak" />
    <footer>
        <p>&copy; @DateTime.Now.Year - Dinner's Ready!</p>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation/dist/additional-methods.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/jquery.unobtrusive-ajax/jquery.unobtrusive-ajax.mim.js"></script>
    <script src="~/lib/microsoftAjax/MicrosoftAjax.js"></script>
    <script src="~/lib/microsoftAjax/MicrosoftMvcAjax.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/alertify.min.js"></script>
    <script src="~/js/wow.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/lib/fontawesome-free-5.15.1-web/js/fontawesome.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("scripts", required: false)

</body>

</html>

DinnersReady/Views/Shared/_test.cshtml
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}

.callout {
  position: fixed;
  bottom: 35px;
  right: 20px;
  margin-left: 20px;
  max-width: 300px;
}

.callout-header {
  padding: 25px 15px;
  background: #555;
  font-size: 30px;
  color: white;
}

.callout-container {
  padding: 15px;
  background-color: #ccc;
  color: black
}

.closebtn {
  position: absolute;
  top: 5px;
  right: 15px;
  color: white;
  font-size: 30px;
  cursor: pointer;
}

.closebtn:hover {
  color: darkgrey;
}
</style>
</head>
<body>

<h2>Callout Messages</h2>

<p>Some content text, blabla.</p>
<p>Some content text, blabla.</p>
<p>Click on the "x" symbol to close the callout message.</p>
<div class="callout">
  <div class="callout-header">Callout Header</div>
  <span class="closebtn" onclick="this.parentElement.style.display='none';">×</span>
  <div class="callout-container">
    <p>Some text to describe the callout message. <a href="#">Learn more</a> or close it if it is in your way.</p>
  </div>
</div>

</body>
</html>